Update yara.yaml

diff --git a/.github/workflows/yara.yaml b/.github/workflows/yara.yaml
--- a/.github/workflows/yara.yaml
+++ b/.github/workflows/yara.yaml
@@ -22,8 +22,13 @@ jobs:
         run: |
           yara -r ${{ github.workspace }}/yara_rules/base64_obfuscation.yar .
 
-      #- name: Fail if obfuscation detected
-      #  if: steps.scan.outcome == 'success' && steps.scan.outputs.stdout != ''
-        #run: |
-          #echo "::error ::Obfuscated (Base64) code detected by YARA. Please review the matches above."
-          #exit 1
+      - name: Run YARA scan (excluding .git)
+        id: scan
+        run: |
+          find . -type f ! -path "./.git/*" -print0 | xargs -0 yara -r ${{ github.workspace }}/yara_rules/base64_obfuscation.yar
+
+      - name: Fail if obfuscation detected
+        if: steps.scan.outcome == 'success' && steps.scan.outputs.stdout != ''
+        run: |
+          echo "::error ::Obfuscated (Base64) code detected by YARA. Please review the matches above."
+          exit 1
